name: Scrape latest data

on:
  schedule:
    - cron:  47 * * * *
  workflow_dispatch: {}
  push:
    paths-ignore:
      - "**.json"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl -XGET "https://www.anz.co.nz/bin/anzconz/rates/?format=JSON&t=$(date +%s)" | jq . > ANZ-rates.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
